# Generated by Django 4.2.1 on 2023-06-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='наименование')),
                ('about', models.CharField(max_length=150, verbose_name='описание')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='наименование')),
                ('about', models.CharField(max_length=150, verbose_name='описание')),
                ('image', models.ImageField(upload_to='products/', verbose_name='превью')),
                ('category', models.CharField(max_length=150, verbose_name='категория')),
                ('price_lot', models.IntegerField(verbose_name='цена за покупку')),
                ('date_create', models.DateTimeField(verbose_name='дата создания')),
                ('date_last_change', models.DateTimeField(verbose_name='дата последнего изменения')),
            ],
        ),
    ]
