# Generated by Django 4.2.1 on 2023-06-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default='2023-06-03', verbose_name='дата создания'),
        ),
    ]
