# Generated by Django 4.2.1 on 2023-06-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_about_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='about',
            field=models.CharField(max_length=1000, verbose_name='описание'),
        ),
    ]
